### ISSUE TITLE
Error Compiling for Nano

### ISSUE THREAD

**Issue by pggood** [EnhancedRadioDevices/DDS#3]
\Arduino\libraries\DDS-master\src\DDS.cpp:48:62: error: default argument given for parameter 1 of 'void DDS::startPhaseAccumulator(bool)' [-fpermissive]
 void DDS::startPhaseAccumulator(bool use_only_timer_2 = false){
                                                             ^
In file included from \Arduino\libraries\DDS-master\src\DDS.cpp:2:0:
\Arduino\libraries\DDS-master\src\DDS.h:146:8: error: after previous specification in 'void DDS::startPhaseAccumulator(bool)' [-fpermissive]
   void startPhaseAccumulator(bool use_only_timer_2 = false);
        ^
exit status 1
Error compiling for board Arduino Nano.

**Comment by per1234** [comment]
What do you have selected in the Tools > Board menu?

**Comment by mogar** [comment]
I'm able to compile the DDS example project for a nano without problems (I don't actually have a nano, I'm just using the verify function in Arduino's software).

What version of the Arduino software are you using?
